version: '2'
services:
    validators:
        image: tianon/true
        restart: "no"
        depends_on:
            - node-1
            - node-2
            - node-3
            - node-4
    normal:
        image: tianon/true
        restart: "no"
        depends_on:
            - node-5
            - node-6
    all:
        image: tianon/true
        restart: "no"
        depends_on:
            - validators
            - normal

    node-1:
        image: ywonline/travis:latest
        container_name: node-1
        volumes:
            - ~/volumes/testnet/travis/nodes/node1:/travis
        command: ["node", "start", "--home", "/travis"]
        ports:
            - 8545:8545
            - 46656:46656
            - 46657:46657
    node-2:
        image: ywonline/travis:latest
        container_name: node-2
        volumes:
            - ~/volumes/testnet/travis/nodes/node2:/travis
        command: ["node", "start", "--home", "/travis"]
        ports:
            - 8555:8545
            - 46666:46656
            - 46667:46657
        depends_on:
            - node-1
    node-3:
        image: ywonline/travis:latest
        container_name: node-3
        volumes:
            - ~/volumes/testnet/travis/nodes/node3:/travis
        command: ["node", "start", "--home", "/travis"]
        ports:
            - 8565:8545
            - 46676:46656
            - 46677:46657
        depends_on:
            - node-1
    node-4:
        image: ywonline/travis:latest
        container_name: node-4
        volumes:
            - ~/volumes/testnet/travis/nodes/node4:/travis
        command: ["node", "start", "--home", "/travis"]
        ports:
            - 8575:8545
            - 46686:46656
            - 46687:46657
        depends_on:
            - node-1
    node-5:
        image: ywonline/travis:latest
        container_name: node-5
        volumes:
            - ~/volumes/testnet/travis/nodes/node5:/travis
        command: ["node", "start", "--home", "/travis"]
        ports:
            - 8585:8545
            - 46696:46656
            - 46697:46657
        depends_on:
            - node-1
    node-6:
        image: ywonline/travis:latest
        container_name: node-6
        volumes:
            - ~/volumes/testnet/travis/nodes/node6:/travis
        command: ["node", "start", "--home", "/travis"]
        ports:
            - 8595:8545
            - 46606:46656
            - 46607:46657
        depends_on:
            - node-1
    smoke-test:
        image: ywonline/web3-cmt:latest
        container_name: client
        depends_on:
            - all

