
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

moniker = "node-2"
fast_sync = true
db_backend = "leveldb"
log_level = "state:info,*:error"

[rpc]
laddr = "tcp://0.0.0.0:46657"

[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "node-1:46656,node-2:46656,node-3:46656,node-4:46656"

[vm]
rpc = true
rpcapi = "cmt,stake,eth,net,web3,personal,admin"
rpcaddr = "0.0.0.0"
rpcport = 8545
ws = false
verbosity = 3

[consensus]
timeout_commit = 10000
