
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

moniker = "local"
fast_sync = true
db_backend = "leveldb"
log_level = "state:info,*:error"

[p2p]
seeds = "18.220.151.169:46656"

[vm]
rpc = true
rpcapi = "cmt,eth,net,web3,personal,admin"
rpcport = 8545
ws = false
verbosity = 3


[consensus]
timeout_commit = 1000
max_block_size_txs = 50000
